markdown: kramdown

description: Mukesh Sahu's Portfolio
title: Mukesh's Portfolio

highlighter: rouge

googleverify: gC8gMLC1UpPDYi2y5KR_9Sq79n4TYMiQM7UcSvtyfms
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
